logging:
  level:
    root: warn
    com.rest.api: info
  file:
    max-history: 7
    path: /home/ec2-user/api/log

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/security?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Gus668400!@

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate:
      hbm2ddl.auto: none
      format_sql: true
    showSql: true
    generate-ddl: false

  url:
    base: http://localhost:8080

  config:
    activate:
      on-profile: dev